version: '3.8'

services:
  server:
    build: ./server
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DATABASE_NAME: gestus
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_IP: postgres
      DATABASE_PORT: 5432
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: password
      ELASTIC_URL: elasticsearch:9200
      SERVER_ADDRESS: 0.0.0.0
    networks:
      - gestus-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gestus
    volumes:
      - gestus_postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - gestus-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      node.name: elasticsearch-prod
      cluster.name: production-cluster
      node.roles: master,data,ingest
      discovery.type: single-node
      bootstrap.memory_lock: 'true'
      network.host: 0.0.0.0
      http.port: 9200
      transport.port: 9300
      xpack.security.enabled: 'true'
      xpack.monitoring.collection.enabled: 'true'
      xpack.watcher.enabled: 'true'
      xpack.security.authc.realms.native.native1.order: 0
      xpack.security.authc.realms.file.file1.order: 1
      ELASTIC_PASSWORD: password
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - gestus_elasticsearch_data:/usr/share/elasticsearch/data
      - gestus_elasticsearch_config:/usr/share/elasticsearch/config
    restart: always
    networks:
      - gestus-network

volumes:
  gestus_elasticsearch_data:
  gestus_elasticsearch_config:
  gestus_postgres_data:

networks:
  gestus-network:
