version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - gestus_server:/data

volumes:
  gestus_server: